### ISSUE TITLE
add private-eye

### ISSUE THREAD

**Issue by afeld** [18F/uswds-jekyll#196]
## Background information

[The logic for it currently exists in the Handbook](https://github.com/18F/handbook/blob/04f251b712cd0f18eaaf2b33de491d729dc7206b/javascripts/application.js#L116-L153), but really, the same 🔒-ing should apply to all TTS microsites. Let's move that logic for [Private Eye](https://github.com/18F/private-eye) into the theme.

## Implementation steps

- [x] Add the logic to the theme
- [x] Confirm it works
- [x] Make the list of URLs configurable
- [ ] Cut a new release
- [ ] Upgrade the Handbook theme
- [ ] Remove logic from the Handbook

## Acceptance criteria

- [ ] Links to private resources in any site that use this theme show up with a 🔒 icon

**Comment by jstrothman** [comment]
**A usability & accessibility note:** We have an [open issue in the UX Guide](https://github.com/18F/ux-guide/issues/225
) to address the usability issue that people frequently don't recognize that the lock means they can not have access to the linked item. We get doc access requests a few times/week from people w/non-gov email addresses who have clicked on the Google 'Request access' button after following the link from the Guide. The Handbook version of Private Eye has a title attribute to explain that the "link is private to TTS," however the [title attribute is problematic for accessibility](https://developer.paciellogroup.com/blog/2010/11/using-the-html-title-attribute/). 

When we have a recommendation for augmenting the icon, we'll add a comment here.

**Comment by tbaxter-18f** [comment]
A question on scope: the plan is to add it to this repo, the uswds-jekyll theme, under the logic that as sites migrate to it, they'll pick it up, right?  I want to confirm that's the scope, not adding it to all sites not currently using it.

**Comment by afeld** [comment]
Right; I was thinking we add it to the uswds-jekyll theme in a way where it's automatically enabled for all sites that use the theme. Making it further configurable by sites that use the theme is a nice-to-have.
